version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - nlp_service
    environment:
      - DATABASE_URL=mongodb://mongo:27017/naarikavach
      - JWT_SECRET=your_jwt_secret

  nlp_service:
    build:
      context: ./nlp_service
      dockerfile: Dockerfile.ai
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: